---

services:
  twostroke:
    image: ghcr.io/gasripper/twostroke:latest
    build: .
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sr1:/dev/sr1
      - /dev/sr2:/dev/sr2
      - /dev/sr3:/dev/sr3
    tmpfs:
      - /tmp
    volumes:
      - ./output:/output
    environment:
      - OUTPUT_DIR=/output
    ports:
      - "1888:1888"
